version: 2
jobs:
  
  test:

    docker:
      - image: circleci/python:3.6
      
    environment:
      - ANSIBLE_HOST_KEY_CHECKING: False
    working_directory: ~/repo

    
    steps:
      
      - checkout
      
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install --upgrade pip
            pip install -r requirements.txt
            sudo apt install rsync
      # Step 3: run linter and tests
      - run:
          name: run tests
          command: |
            . venv/bin/activate
          
            coverage run  --branch --source='.' manage.py test
            coverage report --fail-under=80
            
            coverage html

   
  
  publish:
     docker:
      - image: circleci/python:3.6
      
    environment:
      - ANSIBLE_HOST_KEY_CHECKING: False
    working_directory: ~/repo
      - run:
        name: init .pypirc
        command: |
          echo -e "[pypi]" >> ~/.pypirc
          echo -e "username = NYARAS" >> ~/.pypirc
          echo -e "password = $PYPI_PASSWORD" >> ~/.pypirc      

      - run:
          name: create packages
          command: |
            python3 setup.py sdist bdist_wheel
          #  python setup.py sdist

      - run:
          name: upload to pypi
          command: |
            . venv/bin/activate
            pip install twine
            twine upload dist/*
      
      - add_ssh_keys:
          fingerprints:
              - "9b:27:c9:d9:9f:ce:ea:fb:38:fd:3f:ea:f4:f8:5b:d4"
      
      - run:
          name: executing ansible to AWS server
          command: |
            . venv/bin/activate
            pip install ansible
            ansible-playbook ansible/deploy.yml  -i ansible/hosts


workflows:
  version: 2
  jobs:
    - test
    - publish:
        filter:
          branch:
            master